language: generic
sudo: required
matrix:
  include:
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79 x86_64-clang x86_64-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79 aarch64-linux-android-clang aarch64-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79 x86-clang i686-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79 arm-linux-androideabi-clang arm-linux-androideabi"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz 29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d x86_64-clang x86_64-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz 29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d aarch64-linux-android-clang aarch64-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz 29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d x86-clang i686-linux-android"
    - services:
          docker
      script: docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/fetchbuild.sh https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz 29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d arm-linux-androideabi-clang arm-linux-androideabi"
