language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=8fefeeb46ac366e245b92cb6a4c0da12d0f3b29a687d08c9fe1374defc40e167
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=f56c00b2345cd2e392ade4733e2ca9cb9b0af623
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
    - BITS=64
  matrix:
    - UNUSED=true
    - TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32
    - TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=65e076f0e1d72844f1563ff8d1eaba66109f7fd8
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=65e076f0e1d72844f1563ff8d1eaba66109f7fd8 TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=65e076f0e1d72844f1563ff8d1eaba66109f7fd8 TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=65e076f0e1d72844f1563ff8d1eaba66109f7fd8 TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi BITS=32

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST $BITS"
