language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=27f35245a645f66436a68cc11a9a592c3febabc4a450a286b02f76389ca5cb70
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
  matrix:
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=23b1f768a9b4edcecd75ea01800374c9dd1e95c5
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=23b1f768a9b4edcecd75ea01800374c9dd1e95c5 TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=23b1f768a9b4edcecd75ea01800374c9dd1e95c5 TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=23b1f768a9b4edcecd75ea01800374c9dd1e95c5 TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi
script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $TOOLCHAIN $TARGETHOST"
