language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=2c14fdb2272c9b4bdf4f82020bf369b95f55df448525f85677fdfbc6a6c7c14b
    - BITCOINTARURL=https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz
    - SHA256HASH=e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79
    - TOOLCHAIN=aarch64-linux-android-clang
    - TARGETHOST=aarch64-linux-android
  matrix:
    - UNUSED=true
    - TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi
    - TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android
    - BITCOINTARURL=https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz SHA256HASH=29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d
    - BITCOINTARURL=https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz SHA256HASH=29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d TOOLCHAIN=x86_64-clang TARGETHOST=x86_64-linux-android
    - BITCOINTARURL=https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz SHA256HASH=29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d TOOLCHAIN=x86-clang TARGETHOST=i686-linux-android
    - BITCOINTARURL=https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz SHA256HASH=29038a5fe7b6db48c67949f85f0b43fae55f3f4267863578b1fc526e064d421d TOOLCHAIN=arm-linux-androideabi-clang TARGETHOST=arm-linux-androideabi
script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $BITCOINTARURL $SHA256HASH $TOOLCHAIN $TARGETHOST"
